---
title: java-exception
date: 2020-10-06 22:19:45
tags:
---
Throwable   Error           VirtualMachineeError 
                            AWTError
            Exception       IOException
                            RunntimeException

异常处理

try: 用于捕获异常
catch: 处理try捕获到的异常
finally: 

当try与finally 都有return语句时, 在方法返回之前, finally语句将被执行 并且finally语句的返回值会覆盖原始返回值


